### PR TITLE
update local env setup docs

### PR DESCRIPTION
**Pull request by britt-allen**

### CODE REVIEW

**Comment by britt-allen** [comment]
I tried using the vscode / github integration and it copied these commits from my other PR into this one though that was not intended

**Comment by summer-mothwood** [comment]
> I tried using the vscode / github integration and it copied these commits from my other PR into this one though that was not intended

This is a good issue to know about!

**Comment by ram-kishore-odi** [comment]
Hi @britt-allen, Were you just testing out vscode/github or if there are changes that need to be merged into main ? Please let me know. I am just asking the question to get a better understanding of the context here

**Comment by britt-allen** [comment]
I was testing things out, this PR is closed as it is not relevant

**Pull request closed without merging**
