### PR TITLE
config updates for dbt

### LINKED ISSUE #352: Move profile config to avoid deprecation warning
dbt core deprecated having config values in a `profiles.yml` file, they now want it in the `dbt_project.yml` file.

We should implement the change from [here](https://github.com/cagov/caldata-mdsa-caltrans-pems/pull/356) in this repo.

### PR DESCRIPTION
**Pull request by britt-allen**
fixes #352

### CODE REVIEW

**Comment by JamesSLogan** [comment]
The error message here says "('flags' was unexpected)"...maybe the dbt version in the repo is too low for this change? It looks like `1.6.0` is getting installed. 

Comparing to caltrans, where this change worked:

| repo | string in pyproject.toml | installed version from CI logs |
| -- | -- | -- |
| data-infrastructure | `dbt-core = "~1.6"` | 1.6.0 |
| caltrans | `dbt-core = "~1.7.0"` | 1.7.18 |

**Comment by britt-allen** [comment]
Thank you for flagging James!

**Comment by britt-allen** [comment]
Had to make several updates to address errors i ran into which are captured in the following articles:

- https://discourse.getdbt.com/t/cannot-use-flags-in-dbt-project-yml/13246
- https://github.com/sqlfluff/sqlfluff/issues/5841

**Comment by britt-allen** [comment]
this is ready for another review and merge @JamesSLogan

**Comment by britt-allen** [comment]
the sql fluff errors are not actual errors

**Review by JamesSLogan — APPROVED** [review]
@britt-allen thanks for getting package versions up-to-date. It's weird that sqlfluff is throwing false negatives for those CTEs, it seems like a bug...I disabled that specific test so that CI will pass. Feel free to merge unless you see an issue with this approach

**Comment by jkarpen** [comment]
@JamesSLogan @britt-allen @tnrahim Is this related to the issue Taheer was helping CARB with earlier in the week?

**Comment by britt-allen** [comment]
I don't know. What's up? @jkarpen

**Comment by jkarpen** [comment]
@britt-allen Not sure, could be a totally different issue. Just flagging for Taheer in case there is anything relevant to apply.

**Pull request merged**
