### PR TITLE
Fix load us building footprints 403

### PR DESCRIPTION
**Pull request by ram-kishore-odi**
This PR is for pinning the dependencies to fix the building footprints loader job. The test job which used the test image created from the feature branch succeed.  

Please review the test execution here and let me know if you have any feedback - https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/fargate/detail/33a7f285-d45a-4395-920b-29361ea426e0

### CODE REVIEW

**Comment by ian-r-rose** [comment]
The fix looks good to me, though I don't think that test run exercises the building footprints script. In order to run the script, the batch command must be overridden (this is not well documented!), similar to how it is specified in the Airflow job: https://github.com/cagov/data-infrastructure/blob/12217cbf9e304de24545d7f54bb1afa7a5cab6ef/airflow/dags/geo_reference/load_building_footprints.py#L56

**Comment by ram-kishore-odi** [comment]
> The fix looks good to me, though I don't think that test run exercises the building footprints script. In order to run the script, the batch command must be overridden (this is not well documented!), similar to how it is specified in the Airflow job:
> 
> https://github.com/cagov/data-infrastructure/blob/12217cbf9e304de24545d7f54bb1afa7a5cab6ef/airflow/dags/geo_reference/load_building_footprints.py#L56

@ian-r-rose  Thank you again ! This is what I was about wondering about did not know where to make the update. I will rerun the job after including the override and attached the updated test results

**Comment by ian-r-rose** [comment]
I think the override can be done either with the CLI or with the console

**Comment by ram-kishore-odi** [comment]
> I think the override can be done either with the CLI or with the console

Nice ! I think this is good idea instead of modifying the code. I would like to explore the options to see if there is a way to run the test easily.

**Comment by ian-r-rose** [comment]
@ram-kishore-odi Have you seen the [pre-commit docs](https://cagov.github.io/data-infrastructure/code/local-setup/#installing-pre-commit-hooks) yet?

**Comment by ram-kishore-odi** [comment]
@ian-r-rose Yes I did and fixed the build. Thank you for pointing me to the docs. I am sorry about the multiple commits (that were not related to any real code changes)

**Comment by ram-kishore-odi** [comment]
hi @ian-r-rose,  The job ran as expected this time and did not encounter any loading failures. Please see addition details below

Batch Job
https://us-west-2.console.aws.amazon.com/batch/home?region=us-west-2#jobs/fargate/detail/2bc123b3-f98a-496e-b1b5-5b1c2fb9d45f

Log
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Faws%2Fbatch%2Fjob/log-events/dse-infra-dev-us-west-2-test%2Fdefault%2Fe1b9753b5adc45128d2451f816b2b535

**Review by ian-r-rose — APPROVED** [review]
Looks good, thanks @ram-kishore-odi

**Pull request merged**
