### PR TITLE
Document footprint links

### LINKED ISSUE #222: Generate HTML file with download links for building footprints
This is a small lift that will enhance the usability of the footprints dataset for people less comfortable with using S3 APIs.

This could either be in our public S3 bucket or in our GitHub Pages (or both).

cc @fennisreed for visibility.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Fixes #222.

I used the following Python snippet to help generate the doc table:

```python
import s3fs
import pandas

fs = s3fs.S3FileSystem(anon=True)

fips = pandas.read_csv("https://github.com/kjhealy/fips-codes/raw/master/state_and_county_fips_master.csv")
fips = fips[fips.state == "CA"].assign(fips=fips.fips.astype(str).str.slice(-3))

global_ml_parquet = sorted(
    fs.glob(
        "s3://dof-demographics-dev-us-west-2-public/"
        "global_ml_building_footprints/parquet/**.parquet"
    )
)
global_ml_parquet = ["s3://" + p for p in global_ml_parquet]

global_ml_zip = sorted(
    fs.glob(
        "s3://dof-demographics-dev-us-west-2-public/"
        "global_ml_building_footprints/shp/**.zip"
    )
)
global_ml_zip = ["s3://" + p for p in global_ml_zip]

lines = []
lines.append("| County | GeoParquet (HTTPS) | Shapefile (HTTPS) | GeoParquet (S3) | Shapefile (S3) |")
lines.append("| -------| ------------------ | ----------------- | --------------- | ---------------|")

domain = "https://dof-demographics-dev-us-west-2-public.s3.us-west-2.amazonaws.com/"

for p, s in zip(global_ml_parquet, global_ml_zip):
    county = fips[fips.fips == p.split(".")[-2].split("_")[-1]].iloc[0]["name"]
    hp = domain + "/".join(p.split("/")[-3:])
    hs = domain + "/".join(s.split("/")[-3:])
    lines.append(f"| {county} | [URL]({hp}) | [URL]({hs}) | [URL]({p}) | [URL]({s}) |")
```

Built docs [here](https://cagov.github.io/data-infrastructure/data/footprints/)

### CODE REVIEW

**Comment by ian-r-rose** [comment]
cc @fennisreed for feedback

**Review by britt-allen — APPROVED** [review]
This all looks efficient and great. Thanks for creating this so quickly, @ian-r-rose !

**Comment by ian-r-rose** [comment]
I believe the most recent commit broke the code snippets

**Comment by britt-allen** [comment]
We both ran into the same failure on our commits, I am not sure how mine introduced anything new? @ian-r-rose

**Comment by ian-r-rose** [comment]
> We both ran into the same failure on our commits, I am not sure how mine introduced anything new? @ian-r-rose

This was the python issue in #231, it should work now

**Comment by britt-allen** [comment]
Yes I saw that right after I commented, I misunderstood.

**Review by britt-allen — APPROVED** [review]
Nice catch, ty!

**Pull request merged**
